-- MySQL Script generated by MySQL Workbench
-- 2022年06月25日 10時53分07秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(100) NULL,
  `kana` VARCHAR(100) NULL,
  `email` BLOB NULL COMMENT '★暗号化して格納',
  `password` VARCHAR(255) NULL COMMENT '◆ハッシュ化して格納',
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`payment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`payment` (
  `id` BIGINT NOT NULL,
  `date` DATE NULL,
  `amount` INT NOT NULL,
  `category_id` BIGINT NOT NULL,
  `memo` TEXT NULL,
  `user_id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`payment_category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`payment_category` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment_summary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`payment_summary` ;

CREATE TABLE IF NOT EXISTS `mydb`.`payment_summary` (
  `id` INT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `category_id` BIGINT NOT NULL,
  `year` INT NOT NULL,
  `month` INT NOT NULL,
  `total_amount` INT NOT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_summary_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_payment_summary_payment_category_idx` (`category_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
